# Generated by Django 5.1.3 on 2024-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='reverse_rate',
            field=models.BooleanField(default=False),
        ),
    ]
