# Generated by Django 5.1.3 on 2024-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currency_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=6)),
                ('exchange_rate', models.FloatField(default=0)),
            ],
        ),
    ]
