# Generated by Django 5.1.3 on 2024-11-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
    ]
